//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Supermarket.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stock
    {
        public int id { get; set; }
        public int id_product { get; set; }
        public int quantity { get; set; }
        public Nullable<System.DateTime> supply_date { get; set; }
        public Nullable<System.DateTime> expiration_date { get; set; }
        public decimal purchase_price { get; set; }
        public decimal selling_price { get; set; }
        public Nullable<bool> is_active { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
